CREATE CACHED TABLE EZMENU.PROFILE(
    PROF_NAME CHAR(25),
    PROF_CATGY_SUN CHAR(8),
    PROF_CATGY_MON CHAR(8),
    PROF_CATGY_TUE CHAR(8),
    PROF_CATGY_WED CHAR(8),
    PROF_CATGY_THUR CHAR(8),
    PROF_CATGY_FRI CHAR(8),
    PROF_CATGY_SAT CHAR(8),
    PROF_PREP_SUN CHAR(6),
    PROF_PREP_MON CHAR(6),
    PROF_PREP_TUE CHAR(6),
    PROF_PREP_WED CHAR(6),
    PROF_PREP_THU CHAR(6),
    PROF_PREP_FRI CHAR(6),
    PROF_PREP_SAT CHAR(6)
);
INSERT INTO PUBLIC.PROFILE SELECT * FROM O_14;
DROP TABLE O_M1;
DROP TABLE O_0;
DROP TABLE O_14;
DROP ALIAS READ_BLOB;
DROP ALIAS READ_CLOB;
DROP ALIAS READ_BLOB_DB;
DROP ALIAS READ_CLOB_DB;
CREATE PRIMARY KEY IF NOT EXISTS INFORMATION_SCHEMA.PRIMARY_KEY_2 ON INFORMATION_SCHEMA.LOBS(ID);
CREATE INDEX IF NOT EXISTS INFORMATION_SCHEMA.INDEX_LOB_TABLE ON INFORMATION_SCHEMA.LOBS(TABLE);
CREATE PRIMARY KEY IF NOT EXISTS INFORMATION_SCHEMA.PRIMARY_KEY_3 ON INFORMATION_SCHEMA.LOB_MAP(LOB, SEQ);
CREATE INDEX IF NOT EXISTS INFORMATION_SCHEMA.INDEX_LOB_MAP_DATA_LOB ON INFORMATION_SCHEMA.LOB_MAP(BLOCK, LOB);
CREATE PRIMARY KEY IF NOT EXISTS INFORMATION_SCHEMA.PRIMARY_KEY_9 ON INFORMATION_SCHEMA.LOB_DATA(BLOCK);
ALTER TABLE INFORMATION_SCHEMA.LOBS ADD CONSTRAINT IF NOT EXISTS INFORMATION_SCHEMA.CONSTRAINT_2 PRIMARY KEY(ID) INDEX INFORMATION_SCHEMA.PRIMARY_KEY_2;
ALTER TABLE INFORMATION_SCHEMA.LOB_MAP ADD CONSTRAINT IF NOT EXISTS INFORMATION_SCHEMA.CONSTRAINT_3 PRIMARY KEY(LOB, SEQ) INDEX INFORMATION_SCHEMA.PRIMARY_KEY_3;
ALTER TABLE INFORMATION_SCHEMA.LOB_DATA ADD CONSTRAINT IF NOT EXISTS INFORMATION_SCHEMA.CONSTRAINT_9 PRIMARY KEY(BLOCK) INDEX INFORMATION_SCHEMA.PRIMARY_KEY_9;
---- Transaction log ----
---- Statistics ----
-- page count: 15, free: 0
-- page data bytes: head 168, empty 11322, rows 2846 (22% full)
-- data leaf 46%, 7 page(s)
-- data node 6%, 1 page(s)
-- btree leaf 20%, 3 page(s)
-- free list 6%, 1 page(s)
